### ISSUE TITLE
IndexError: too many indices for tensor of dimension 2

### ISSUE THREAD

**Issue by zyx792726304** [idstcv/DR_loss#9]
I run drloss on voc datasets with yolo,I replaced focal loss with drloss.
My input shape:
logits.shape = [564,20]
targets.shape = [564,20]

However:
Traceback (most recent call last):
  File "a.py", line 17, in <module>
    print(drloss(input_tensor,target_tensor))
  File "D:\anaconda\envs\zyx\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "utils\loss.py", line 235, in forward
    pos_prob = logits[pos_ind].sigmoid()
IndexError: too many indices for tensor of dimension 2

What should I do to fix this?

**Comment by Mantas-Pimpe** [comment]
How did you solve this?
